# Generated by Django 4.1.5 on 2023-01-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemliked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemliked',
            options={'verbose_name': 'Item Liked', 'verbose_name_plural': 'Items Liked'},
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='items/item_image'),
        ),
        migrations.AlterField(
            model_name='itemliked',
            name='items',
            field=models.ManyToManyField(related_name='liked_items', to='items.item'),
        ),
    ]
