# Generated by Django 4.1.5 on 2023-01-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_itemliked_options_alter_item_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
